import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import Header from '../components/ui/header';
import Providers from '@/components/Providers';
import Head from 'next/head';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={fontSans.className}>
      <Providers>
        <body className='sticky top-0 bg-background text-foreground'>
          <Header />
          <main className='flex flex-col items-center'>{children}</main>
        </body>
      </Providers>
    </html>
  );
}
